### ISSUE TITLE
Support failOnWarnings

### ISSUE THREAD

**Issue by brianwyka** [Optum/sourcehawk-maven#1]
Add support for `failOnWarnings` build configuration which allows the build to fail when there are only warnings.

**User property:** `sourcehawk.scan.failOnWarnings`

**Default:** `false`

(Available since https://github.com/Optum/sourcehawk/releases/tag/v0.1.5)

**Comment by ctoestreich** [comment]
@brianwyka  Adding this to my incoming PR
